configfile: "config/config.yaml"

FILENAMES = ['A','B','C']
OUTPUTS_DIR = config['outputs_dir']
DATA_DIR = config['data_dir']
#print(OUTDIR)

rule all:
	input:
		expand("/Users/mhb8436/snake/test4/results/{OUTDIR}/wc_all.png", OUTDIR=OUTPUTS_DIR)

rule count:
	input:
		"/Users/mhb8436/snake/test4/resources/{filename}.txt"
	output:
		"/Users/mhb8436/snake/test4/results/{OUTDIR}/wc_{filename}.txt"
	shell:
		"wc -w {input} > {output}"

rule concat:
	input:
		expand('/Users/mhb8436/snake/test4/results/{OUTDIR}/wc_{filename}.txt', filename=FILENAMES, OUTDIR=OUTPUTS_DIR)
	output:
		expand("/Users/mhb8436/snake/test4/results/{OUTDIR}/wc_all.csv", OUTDIR=OUTPUTS_DIR)
	script:
		"scripts/concat.py"

rule plot:
	input:
		expand("/Users/mhb8436/snake/test4/results/{OUTDIR}/wc_all.csv", OUTDIR=OUTPUTS_DIR)
	output:
		expand("/Users/mhb8436/snake/test4/results/{OUTDIR}/wc_all.png", OUTDIR=OUTPUTS_DIR)
	script:
		"scripts/plot.py"

